/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
public:
    char findTheDifference(string s, string t) 
    {
        int ascii_sum_s =0;
        int ascii_sum_t=0;
        
        for(int i=0; i<s.length(); i++){
            ascii_sum_s += s[i];
        }
        for(int i=0; i<t.length(); i++){
            ascii_sum_t += t[i];
        }
        
        char ch = ascii_sum_t - ascii_sum_s;
        return ch;

    }
};